# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: iryna
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: shop
# "service" is the name of this project. This will also be added to your AWS resource names.
service: products-service

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
